### ISSUE TITLE
Get Started

### ISSUE THREAD

**Issue by nanocreaator** [Cretezy/Noderize#19]
Hi, I just followed your get started and have some issues.

$ yarn watch
yarn run v1.7.0
$ noderize-scripts watch
● start watch › Watching...

ℹ info watch › Building...

Hash: be7c613fd893f4d1b89b
Time: 781ms
Built at: 2018-05-24 15:20:19
   Asset      Size  Chunks  Chunk Names
index.js  2.17 KiB       0  index.js
 + 1 hidden asset
Entrypoint index.js = index.js index.js.map

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/index.js
Module build failed: Error: [BABEL] /Apps/test2/src/index.js: The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators (While processing: "/Apps/test2/node_modules/@babel/plugin-proposal-decorators/lib/index.js")
    at _default (/Apps/test2/node_modules/@babel/plugin-proposal-decorators/lib/index.js:44:11)
    at /Apps/test2/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor (/Apps/test2/node_modules/@babel/core/lib/config/full.js:163:14)
    at cachedFunction (/Apps/test2/node_modules/@babel/core/lib/config/caching.js:42:19)
    at loadPluginDescriptor (/Apps/test2/node_modules/@babel/core/lib/config/full.js:198:28)
    at config.plugins.map.descriptor (/Apps/test2/node_modules/@babel/core/lib/config/full.js:64:16)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Apps/test2/node_modules/@babel/core/lib/config/full.js:63:38)
    at loadFullConfig (/Apps/test2/node_modules/@babel/core/lib/config/full.js:106:6)
    at process.nextTick (/Apps/test2/node_modules/@babel/core/lib/transform.js:28:33)
 @ multi ./src/index.js

● start start › Starting...

✖ error start › Start file does not exists.

**Comment by Cretezy** [comment]
Seems like you aren't running the latest version. Mind telling me what version of scripts you are using?

**Comment by Cretezy** [comment]
Alright, v0.7.0 is out, fixes this!

**Comment by nanocreaator** [comment]
I’ll try again and keep you posted if some problem happens.
Thanks for the update!

**Comment by dbrudnicki** [comment]
Thanks Charles.

- David
