### ISSUE TITLE
format script generating UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by sc0ttwad3** [Cretezy/Noderize#2]
New application created  

```
c:\projects\typescript
λ yarn create noderize noderize-first
λ cd noderize-first\
λ yarn build
```

then running the format script ```yarn format``` is generating a warning. Looks like it's in **@noderize\scripts\dist\index.js**

```
c:\projects\typescript\noderize-first
λ yarn run format
yarn run v1.5.1
$ noderize-scripts format
[INFO] Formatting...
(node:43464) UnhandledPromiseRejectionWarning: ReferenceError: getOptions is not defined
    at Object._callee$ (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:1865:13)
    at tryCatch (c:\projects\typescript\noderize-first\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\projects\typescript\noderize-first\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\projects\typescript\noderize-first\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\projects\typescript\noderize-first\node_modules\@babel\runtime\helpers\asyncToGenerator.js:12:30)
    at _next (c:\projects\typescript\noderize-first\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:9)
    at c:\projects\typescript\noderize-first\node_modules\@babel\runtime\helpers\asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (c:\projects\typescript\noderize-first\node_modules\core-js\library\modules\_export.js:35:28)
    at Object.<anonymous> (c:\projects\typescript\noderize-first\node_modules\@babel\runtime\helpers\asyncToGenerator.js:7:12)
    at Object.format (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:1893:17)
    at Object.<anonymous> (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:1337:19)
    at __webpack_require__ (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:31:30)
    at Object.<anonymous> (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:1294:18)
    at __webpack_require__ (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:31:30)
    at module.exports (c:\projects\typescript\noderize-first\node_modules\@noderize\scripts\dist\index.js:74:18)
(node:43464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.87s.
```

Other scripts are fine, and app runs correctly.  Great Project, BTW!

**Comment by Cretezy** [comment]
Alright, I'll submit a fix soon. Hold tight!

**Comment by sc0ttwad3** [comment]
It's probably just complaining about exception thrown within .then handler, .catch handler, or in the function passed to the new Promise being swallowed unless manually handled. Let me know if you ever want any assistance. 

Really look forward to using this project! A huge time saver as I have something similar I've been working on and use to scaffold up projects, using the same tool stack, but still tweaking on it and nowhere near the polished state or functionality of **noderize**

**Comment by Cretezy** [comment]
https://github.com/Cretezy/Noderize/blob/master/packages/scripts/src/scripts/format.js#L9
I'm simply not importing `getOptions`.

**Comment by Cretezy** [comment]
Fixed in https://github.com/Cretezy/Noderize/commit/26a17de2fc0b197b35a1f19aa9bf4c321255d49c.

Publishing v0.4.2 in a minute.

**Comment by Cretezy** [comment]
Published. Thanks for the report! Upgrade to v0.4.2 and enjoy!

**Comment by sc0ttwad3** [comment]
Great. Was going to ask if you needed to add ```import [ getOptions } from "../options.js"``` to format.js, if I was following correctly, but you're way ahead of me.  

Thx, I'll check it out.

**Comment by sc0ttwad3** [comment]
Does the ```clean``` script need to import ```options.js``` as well?  It looks like it uses ```options.distDirectory``` and running it is giving a reference error, now:

```
λ yarn clean
yarn run v1.5.1
$ noderize-scripts clean
[INFO] Cleaning...
[ERROR] Error deleting files.
ReferenceError: options is not defined
    at Object._callee$ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1938:66)
    at tryCatch (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:12:30)
    at _next (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:9)
    at c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (c:\projects\typescript\second-noderize\node_modules\core-js\library\modules\_export.js:35:28)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:7:12)
    at Object.clean (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1959:17)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1337:19)
    at __webpack_require__ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:31:30)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1294:18)
    at __webpack_require__ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:31:30)
    at module.exports (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:74:18)
Done in 1.53s.
```

**Comment by Cretezy** [comment]
Yep. Wanna do the PR? :)

-------- Original Message --------

**Comment by sc0ttwad3** [comment]
Sure let me look into it.  I actually put the error in a new issue to keep them separate. Hope that's the way you wanted it.

**Comment by Cretezy** [comment]
Yep, perfect!

-------- Original Message --------
