### ISSUE TITLE
clean script is generating a ReferenceError: options is not defined

### ISSUE THREAD

**Issue by sc0ttwad3** [Cretezy/Noderize#3]
Does the clean script need to import ```options.js``` as well? It looks like it uses ```options.distDirectory``` and running it is giving a reference error, now:

```
λ yarn clean
yarn run v1.5.1
$ noderize-scripts clean
[INFO] Cleaning...
[ERROR] Error deleting files.
ReferenceError: options is not defined
    at Object._callee$ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1938:66)
    at tryCatch (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\projects\typescript\second-noderize\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:12:30)
    at _next (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:9)
    at c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (c:\projects\typescript\second-noderize\node_modules\core-js\library\modules\_export.js:35:28)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@babel\runtime\helpers\asyncToGenerator.js:7:12)
    at Object.clean (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1959:17)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1337:19)
    at __webpack_require__ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:31:30)
    at Object.<anonymous> (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:1294:18)
    at __webpack_require__ (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:31:30)
    at module.exports (c:\projects\typescript\second-noderize\node_modules\@noderize\scripts\dist\index.js:74:18)
Done in 1.53s.
```

**Comment by Cretezy** [comment]
https://github.com/Cretezy/Noderize/pull/4
